ci: break the CD/CI functionality into separate workflows

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,8 +1,9 @@
-name: Continuous Deployment
+name: Continuous Integration
 
 on:
-  push:
+  pull_request:
     branches: [main]
+  workflow_dispatch:
 
 jobs:
   flatter:
@@ -23,6 +24,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Setup GPG
+        if: ${{ !github.event.repository.fork }}
         id: gpg
         uses: crazy-max/ghaction-import-gpg@v6
         with:
@@ -37,6 +39,7 @@ jobs:
         with:
           files: |
             tests/flatpak/ca.andyholmes.Flatter.json
+            tests/flatpak/ca.andyholmes.Flatter.Failure.yml
           arch: ${{ matrix.arch }}
           gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
           upload-bundles: true
@@ -46,20 +49,29 @@ jobs:
             tests/default.css
             CNAME
 
-  deploy:
-    name: Deploy
-    if: ${{ github.event_name != 'pull_request' }}
-    runs-on: ubuntu-latest
-    needs: flatter
-    permissions:
-      pages: write
-      id-token: write
-    environment:
-      name: github-pages
-      url: ${{ steps.deployment.outputs.page_url }}
+      - name: Test Success
+        uses: andyholmes/flatter@main
+        with:
+          files: |
+            tests/flatpak/ca.andyholmes.Flatter.json
+          arch: ${{ matrix.arch }}
+          cache-key: ''
+          run-tests: true
 
-    steps:
-      - name: GitHub Pages
-        id: deployment
-        uses: actions/deploy-pages@v4
+      - name: Test Failure
+        id: test-failure
+        continue-on-error: true
+        uses: andyholmes/flatter@main
+        with:
+          files: |
+            tests/flatpak/ca.andyholmes.Flatter.Failure.yml
+          arch: ${{ matrix.arch }}
+          cache-key: ''
+          run-tests: true
+
+      - name: Assert Test Failure
+        if: ${{ steps.test-failure.outcome != 'failure' }}
+        run: |
+          echo "The 'Test Failure' step did not fail as expected." >> $GITHUB_STEP_SUMMARY
+          exit 1
 
